### PR TITLE
fix def stats for missing fumble stats

### LINKED ISSUE #382: `calculate_player_stats_def()` fails if certain stats are missing in pbp
``` r
pbp <- nflfastR::build_nflfastR_pbp("2022_01_BUF_LA")
#> ── DONE 

nflfastR::calculate_player_stats_def(pbp)
#> Error in `pivot_longer_spec()`:
#> ! Can't combine `fumbled_1_player_id` <logical> and `fumbled_2_player_id` <character>.

#> Backtrace:
#>      ▆
#>   1. ├─nflfastR::calculate_player_stats_def(pbp)
#>   2. │ └─... %>% dplyr::ungroup() at nflfastR/R/aggregate_game_stats_def.R:278:2
#>   3. ├─dplyr::ungroup(.)
#>   4. ├─dplyr::summarise(...)
#>   5. ├─dplyr::group_by(., .data$season, .data$week, .data$team, .data$player_id)
#>   6. ├─dplyr::rename(., fumble = "fumbled", fumble_recovery_own = "fumble_recovery")
#>   7. ├─dplyr::filter(., !is.na(.data$player_id))
#>   8. ├─tidyr::pivot_wider(...)
#>   9. ├─dplyr::mutate(...)
#>  10. ├─tidyr::pivot_longer(...)
#>  11. └─tidyr:::pivot_longer.data.frame(...)
#>  12.   └─tidyr::pivot_longer_spec(data, spec, names_repair = names_repair, values_drop_na = values_drop_na,
#>   values_ptypes = values_ptypes, values_transform = values_transform)
#>  13.     └─vctrs::vec_ptype_common(...)
#>  14.       └─vctrs (local) `<fn>`()
#>  15.         └─vctrs::vec_default_ptype2(...)
#>  16.           └─vctrs::stop_incompatible_type(...)
#>  17.             └─vctrs:::stop_incompatible(...)
#>  18.               └─vctrs:::stop_vctrs(...)
#>  19.                 └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = vctrs_error_call(call))
```

<sup>Created on 2022-09-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by mrcaseb**
fixes #382 

-- ensures that `fumbled_1_player_id` is always of type character,
-- allows column renaming even if data is missing by row binding a dummy tibble

### CODE REVIEW

File: R/aggregate_game_stats_def.R [hunk 1]
```diff
@@ -305,11 +305,18 @@ calculate_player_stats_def <- function(pbp, weekly = FALSE) {
       values_fn = sum,
       values_fill = 0
     ) %>%
-    dplyr::filter(!is.na(.data$player_id)) %>%
+    # Renaming fails if the columns don't exist. So we row bind a dummy tibble
+    # including the relevat columns. The row will be filtered after renaming
+    dplyr::bind_rows(
+      tibble::tibble(
+        player_id = NA_character_, fumbled = 0, fumble_recovery = 0
```
Comment (tanho63) [inline R/aggregate_game_stats_def.R:312]: what about using numeric(0) ?

Comment (mrcaseb) [reply R/aggregate_game_stats_def.R:312]: irrelevant because that row get's filtered out 4 lines later

Comment (mrcaseb) [reply R/aggregate_game_stats_def.R:312]: or do you mean from a memory allocation perspective?

Comment (tanho63) [reply R/aggregate_game_stats_def.R:312]: also reduces need to filter since it just creates the column and doesn’t add the row?

Comment (mrcaseb) [reply R/aggregate_game_stats_def.R:312]: the filter was in there anyway. We can't remove it. But I will make them numeric(0)

**Review by tanho63 — APPROVED** [review]
lgtm
